version: '3.8'

services:
  nginx:
    container_name: masoi-nginx
    image: nginx:latest
    ports:
      - '8081:80'
      - '8443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/masoi.hoatepdev.site/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/masoi.hoatepdev.site/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - app
    networks:
      - masoi-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masoi-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PORT=${PORT}
    ports:
      - '3600:4001'
    networks:
      - masoi-net

networks:
  masoi-net:
    driver: bridge
