version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masoi-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PORT=${PORT}
    ports:
      - '3600:3100'
    networks:
      - masoi-net

networks:
  masoi-net:
    driver: bridge
